name: wikmind

services:
  postgres:
    image: postgres:17
    container_name: wikmind-postgres
    environment:
      POSTGRES_DB: wikmind
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - wikmind-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  wikmind-postgres-data: