ALTER TABLE workspaces
    ADD COLUMN starred BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE workspaces
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE workspaces
    ADD COLUMN archived_at TIMESTAMP WITH TIME ZONE;